[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#212121"
critical_bg = "#E57373"
critical_fg = "#E57373"
good_bg = "#A6BC69"
info_bg = "#FAC863"

[icons] 
name = "awesome5"

[[block]]
block = "music"
buttons = ["play", "next"]
hide_when_empty = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}/{mem_total;G}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
critical_mem = 95
[block.theme_overrides]
idle_bg = "#C594C5"
idle_fg = "#212121"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#C594C5"
idle_fg = "#212121"

[[block]]
block = "load"
interval = 1
format = "{1m}"
[block.theme_overrides]
idle_bg = "#C594C5"
idle_fg = "#212121"

[[block]]
block = "xrandr"
interval = 2
icons = true
resolution = true
[block.theme_overrides]
idle_bg = "#5FB3B3"
idle_fg = "#212121"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
[block.theme_overrides]
idle_bg = "#5FB3B3"
idle_fg = "#000000"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"
[block.theme_overrides]
idle_bg = "#5FB3B3"
idle_fg = "#000000"

[[block]]
block = "battery"
[block.theme_overrides]
idle_bg = "#5FB3B3"
idle_fg = "#212121"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
