icons = "awesome"

[theme]
name = "solarized-dark"

[theme.overrides]
#alternating_tint_fg = "#FFFFF"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp2s0"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB/{MTg}GB"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "xrandr"
interval = 2
icons = true
resolution = true

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

