[theme]
theme = "solarized-dark"

[theme.overrides]
idle_bg = "#212121"
critical_bg = "#e76f51"
warning_bg = "#f9844a"
good_bg = "#A6BC69"
info_bg = "#FAC863"
separator = "<span font='13.5'></span>"

[icons] 
icons = "awesome6"

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"
[block.icons_overrides]
tea = "\uf017"
[block.theme_overrides]
idle_bg = "#8ae9fd"
idle_fg = "#212121"

[[block]]
block = "pomodoro"
format = " $icon { $message|} "
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false
[block.icons_overrides]
pomodoro = "\uf1da"
[block.theme_overrides]
idle_bg = "#e76f51"
idle_fg = "#212121"

[[block]]
block = "music"
format = " $icon  {$player.str(max_w:7): $combo.str(max_w:20,rot_interval:0.5) $play $next |}"
[block.theme_overrides]
idle_bg = "#FAC863"
idle_fg = "#212121"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon /home $available.eng(w:2) "
[block.theme_overrides]
idle_bg = "#577590"
idle_fg = "#212121"

[[block]]
block = "memory"
interval = 5
warning_mem = 80
critical_mem = 95
format = " $icon $mem_used.eng(prefix:M)/$mem_total.eng(prefix:M) "
format_alt = " $icon_swap $swap_used.eng(prefix:M)/$swap_total.eng(prefix:M) "
[block.theme_overrides]
idle_bg = "#C594C5"
idle_fg = "#212121"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#7678ed"
idle_fg = "#212121"

[[block]]
block = "load"
interval = 1
format = " $icon 1min avg: $1m.eng(w:4) "
[block.theme_overrides]
idle_bg = "#C594C5"
idle_fg = "#212121"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
[block.theme_overrides]
idle_bg = "#f28482"
idle_fg = "#212121"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#f28482"
idle_fg = "#212121"

[[block]]
block = "backlight"
[block.theme_overrides]
idle_bg = "#f9c74f"
idle_fg = "#212121"

[[block]]
block = "custom"
command = "echo \uf030"
interval = "once"
[[block.click]]
button = "left"
cmd = "~/base/scripts/screenshot.sh"
[block.theme_overrides]
idle_bg = "#90be6d"
idle_fg = "#212121"

[[block]]
block = "custom"
command = "echo \ue163"
interval = "once"
[[block.click]]
button = "left"
cmd = "~/base/scripts/update_dpi.sh"
[block.theme_overrides]
idle_bg = "#43aa8b"
idle_fg = "#212121"

[[block]]
block = "battery"
[block.theme_overrides]
idle_bg = "#577590"
idle_fg = "#212121"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
