[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#212121"
critical_bg = "#e57373"
good_bg = "#a6bc69"
info_bg = "#fac863"

[icons] 
name = "awesome5"

[[block]]
block = "music"
buttons = ["play", "next"]
hide_when_empty = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB/{MTg}GB"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
critical_mem = 95
[block.color_overrides]
idle_bg = "#c594c5"
idle_fg = "#212121"

[[block]]
block = "cpu"
interval = 1
[block.color_overrides]
idle_bg = "#c594c5"
idle_fg = "#212121"

[[block]]
block = "load"
interval = 1
format = "{1m}"
[block.color_overrides]
idle_bg = "#c594c5"
idle_fg = "#212121"

[[block]]
block = "xrandr"
interval = 2
icons = true
resolution = true
[block.color_overrides]
idle_bg = "#5fb3b3"
idle_fg = "#212121"

[[block]]
block = "sound"
[block.color_overrides]
idle_bg = "#5fb3b3"
idle_fg = "#00000"

[[block]]
block = "battery"
[block.color_overrides]
idle_bg = "#5fb3b3"
idle_fg = "#212121"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
