" VIM configuration flo
call pathogen#infect()

set encoding=UTF-8

" Disable compatibility with Vi
set nocompatible

" Display 
set title 
set number
set ruler
set wrap 

set scrolloff=3

" indent properly
set tabstop=4
set shiftwidth=4
set expandtab

" Search config
set ignorecase
set smartcase
set incsearch
set hlsearch  

" Beep
set visualbell
set noerrorbells

" set t_Co=16
syntax enable
" let g:solarized_termcolors=16
set background=dark " dark|light "
colorscheme solarized
filetype plugin indent on
set cursorline
set colorcolumn=80

set backspace=indent,eol,start

set nocscopeverbose 
let mapleader="," 
nmap <silent> <Leader>of :FSHere<CR> 
nmap <silent> <Leader>or :FSSplitRight<CR> 

" ctrl-n to toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

"let g:ctrlp_map = ’<leader>c’
" Default parameters for ack
"let g:ackprg="ack -H --nocolor --nogroup --column" 
" Put a marker and search
"nmap <leader>j mA:Ack<space>
" Put a marker and search current word under cursor
"nmap <leader>j amA:Ack "<C-r>=expand("<cword>")<cr>"
"nmap <leader>j amA:Ack "<C-r>=expand("<cWORD>")<cr>"

" new split appears below or right (feels more natural)
set splitbelow
set splitright

" gitgutter settings
hi clear signColumn

" airline settings
" always show airline status bar
set laststatus=2
" show for tabs
let g:airline#extensions#tabline#enabled = 1
" use patched font
let g:airline_powerline_fonts = 1
" enable jsx syntax highlighting
let g:jsx_ext_required = 0

set nofoldenable

cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

au BufRead,BufNewFile *.kt  set filetype=kotlin
au BufRead,BufNewFile *.jet set filetype=kotlin
au Syntax kotlin source ~/.vim/syntax/kotlin.vim

