# Path to your oh-my-zsh installation.
export ZSH=/home/flo/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="blinks"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export ANDROID_HOME=$HOME/dev/tools/android-sdk-linux

export ANDROID_NDK_HOME=$HOME/dev/utils/android-ndk-r10e

export PATH="/usr/lib64/ccache/bin:/home/flo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/flo/dev/tools/android-studio/bin:/home/flo/taf/dev/utils:/home/flo/dev/tools/android-sdk-linux/platform-tools:/home/flo/dev/tools/android-sdk-linux/tools:/home/flo/dev/utils:/home/flo/dev/tools/astyle/build/gcc/bin:/usr/bin/vendor_perl/:/usr/local/go/bin:/home/flo/.gem/ruby/2.3.0/bin:/home/flo/dev/tools/android-sdk-linux/build-tools/23.0.3/"
# export MANPATH="/usr/local/man:$MANPATH"
export GIT_EDITOR=vim

export JAVA_HOME='/usr/lib/jvm/java-8-openjdk'
export STUDIO_JDK='/usr/lib/jvm/java8-oracle'

export QT_SELECT=5

#export QMAKE='/home/flo/dev/utils/qt-4.8.6/qmake'

alias gw='./gradlew'

alias woof='/usr/bin/python2.7 /home/flo/dev/tools/woof'

export GREP_COLOR=31
alias grep='grep --color=auto'

alias ls='ls --color=auto'
alias ll='ls --color=auto -lh'
alias la='ls --color=auto -lah'
alias lll='ls --color=auto -lh | less'
#alias autorandr='~/dev/utils/autorandr/autorandr'
source $ZSH/oh-my-zsh.sh

alias tigs='tig status'
alias spotifyScaled='spotify --force-device-scale-factor=1.5'
alias steamLibFix='LIBGL_DRI3_DISABLE=1 steam'
alias hangout='google-chrome-stable --app-id=knipolnnllmklapflnccelgolnpehhpl'
alias postman='google-chrome-stable --app-id=fhbjgbiflinjbdggehcddcbncdddomop'
alias pocket='google-chrome-stable --app-id=mjcnijlhddpbdemagnpefmlkjdagkogk'

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

export VISUAL='vim'

export USE_CCACHE=1
export CCACHE_DIR=/home/flo/.ccache

export GOPATH=/home/flo/dev/workspace/go_workspace

#start ssh-agent
if ! pgrep -u $USER ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
        eval $(<~/.ssh-agent-thing)
fi
ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
