CURRENT_DIR = $(shell pwd)

SCRIPTS_DIR = $(HOME)/bin

scripts:
	mkdir -p $(SCRIPTS_DIR)
	ln -sf $(CURRENT_DIR)/screens.sh $(SCRIPTS_DIR)/screens
	ln -sf $(CURRENT_DIR)/change_volume.sh $(SCRIPTS_DIR)/vol
	ln -sf $(CURRENT_DIR)/windows.sh $(SCRIPTS_DIR)/tunnel
